### ISSUE TITLE
Unable to access the display application after success deployment.

### ISSUE THREAD

**Issue by lkumili** [oneops/display#153]
Even though deployment is success we are seeing below error at /var/log/httpd/error.log. As agent was not started successfully we are unable to access it.

 *** Passenger could not be initialized because of this error: Unable to start the Phusion Passenger watchdog because its executable (/usr/local/share/gems/gems/passenger-4.0.59/buildout/agents/PassengerWatchdog) does not exist. This probably means that your Phusion Passenger installation is broken or incomplete, or that your 'PassengerRoot' directive is set to the wrong value. Please reinstall Phusion Passenger or fix your 'PassengerRoot' directive, whichever is applicable. To learn how to fix 'PassengerRoot', please read https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#PassengerRoot

As part of Ruby component passenger is installed but its not installing agent.

**Comment by mosabua** [comment]
Issue tracking is migrated to Walmart JIRA and https://github.com/oneops/oneops.
