### ISSUE TITLE
Issue with Operation Metrics are not displaying on any of the page..Geeting HTTP/1.1 404 not found in the log

### ISSUE THREAD

**Issue by rajucgi** [oneops/display#180]
**Rail.log:**
<- "POST /sensor/rest/ops/states HTTP/1.1\r\nContent-Type: application/json\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAccept: */*\r\nUser-Agent: Ruby\r\nConnection: keep-alive\r\nKeep-Alive: 30\r\nHost: sensor:8080\r\nContent-Length: 78\r\n\r\n"
<- "[135350,158349,158346,173770,173773,173776,173446,173443,173764,173761,173767]"
-> "HTTP/1.1 404 Not Found\r\n"
-> "Server: Apache-Coyote/1.1\r\n"
-> "Content-Length: 0\r\n"
-> "Date: Mon, 10 Apr 2017 17:49:24 GMT\r\n"
-> "\r\n"
reading 0 bytes...
-> ""
read 0 bytes

**Development.log**

Started GET "/democloud/reports/health?format=json" for 27.59.50.120 at 2017-04-10 17:46:09 +0000
Processing by ReportsController#health as JSON
  Parameters: {"org_name"=>"democloud"}
  User Load (0.4ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = 1  ORDER BY "users"."id" ASC LIMIT 1
  Organization Load (0.1ms)  SELECT  "organizations".* FROM "organizations"  WHERE "organizations"."id" = $1 LIMIT 1  [["id", 1]]
  HTTP Get (17.3ms)  http://cmsapi:8080/adapter/rest/cm/simple/relations?nsPath=%2Fdemocloud&recursive=true&relationName=manifest.Requires
  HTTP Post (0.9ms)  http://sensor:8080/sensor/rest/ops/components/states/count
Failed to retrieve component operations states: Failed.  Response code = 404.  Response message = Not Found.
Completed 200 OK in 38ms (Views: 0.4ms | ActiveRecord: 0.5ms | Http: 18.3ms)

**Comment by mosabua** [comment]
Issue tracking is migrated to Walmart JIRA and https://github.com/oneops/oneops.
