### ISSUE TITLE
Cost Explorer

### ISSUE THREAD

**Issue by lkhusid** [oneops/display#4]
Add Cost Explorer page and Cost Summary sections to organization and assembly pages.

**Comment by yrmallu** [comment]
I'm getting the following error in cost summary 

Started GET "/devinstance/organization/cost?authenticity_token=[FILTERED]" for 121.242.18.68 at 2017-04-25 12:39:26 +0000
Processing by OrganizationController#cost as JS
  Parameters: {"authenticity_token"=>"[FILTERED]", "org_name"=>"devinstance"}
  User Load (0.5ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = 1  ORDER BY "users"."id" ASC LIMIT 1
  Organization Load (0.2ms)  SELECT  "organizations".* FROM "organizations"  WHERE "organizations"."id" = $1 LIMIT 1  [["id", 1]]
  HTTP Post (2.1ms)  http://search:9200/cost/ci/_search
Failed to fetch 'cost' for nsPath=/devinstance, date range=[2017-04-01, 2017-04-25: Failed.  Response code = 404.  Response message = Not Found.
  HTTP Post (25.5ms)  http://search:9200/cms-all/ci/_search
Failed to fetch 'cost_rate' for nsPath /devinstance*bom/*: Failed.  Response code = 500.  Response message = Internal Server Error.
  HTTP Post (1.0ms)  http://search:9200/cost-*/ci/_search
Failed to fetch 'cost_time_histogram' for nsPath=/devinstance, date range=[2017-02-01, 2017-04-25], interval=month: undefined method `[]' for nil:NilClass
  Rendered base/cost/_cost.html.erb (0.2ms)
  Rendered base/cost/cost.js.erb (0.8ms)
Completed 200 OK in 43ms (Views: 4.0ms | ActiveRecord: 0.7ms | Http: 28.7ms)

**Comment by yrmallu** [comment]
@lkhusid Started GET "/devinstance/organization/cost?authenticity_token=[FILTERED]" for 121.242.18.68 at 2017-04-25 12:39:26 +0000
Processing by OrganizationController#cost as JS
  Parameters: {"authenticity_token"=>"[FILTERED]", "org_name"=>"devinstance"}
  User Load (0.5ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = 1  ORDER BY "users"."id" ASC LIMIT 1
  Organization Load (0.2ms)  SELECT  "organizations".* FROM "organizations"  WHERE "organizations"."id" = $1 LIMIT 1  [["id", 1]]
  HTTP Post (2.1ms)  http://search:9200/cost/ci/_search
Failed to fetch 'cost' for nsPath=/devinstance, date range=[2017-04-01, 2017-04-25: Failed.  Response code = 404.  Response message = Not Found.
  HTTP Post (25.5ms)  http://search:9200/cms-all/ci/_search
Failed to fetch 'cost_rate' for nsPath /devinstance*bom/*: Failed.  Response code = 500.  Response message = Internal Server Error.
  HTTP Post (1.0ms)  http://search:9200/cost-*/ci/_search
Failed to fetch 'cost_time_histogram' for nsPath=/devinstance, date range=[2017-02-01, 2017-04-25], interval=month: undefined method `[]' for nil:NilClass
  Rendered base/cost/_cost.html.erb (0.2ms)
  Rendered base/cost/cost.js.erb (0.8ms)
Completed 200 OK in 43ms (Views: 4.0ms | ActiveRecord: 0.7ms | Http: 28.7ms)

**Comment by lkhusid** [comment]
Is ElasticSearch up and running?   If so, is it accessible by short CNAME 'search' as in the URLs above?   The URL location of ES data source is controlled by *SEARCH_SITE* environment variable and defaults to 'http://search:9200/' if not set.    If ES is up and running but not accessible by this default url, set up the env varialble (SEARCH_SITE) which points to ES.

**Comment by lkhusid** [comment]
Also, make sure that you have cloud service offerings configured under corresponding cloud service configuration.
There may also be necessary to set up a separate cost batch job to calculate  cost (per day).   But if offerings are configured you should see at least cost rate information in UI (given that ES is running and accessible).

**Comment by yrmallu** [comment]
Can you please share me the steps to setup and elastic search and logstash ?

On 25 Apr 2017 8:49 pm, "Lev" <notifications@github.com> wrote:

Is ElasticSearch up and running? If so, is it accessible by short CNAME
'search' as in the URLs above? The URL location of ES data source is
controlled by *SEARCH_SITE* environment variable and defaults to '
http://search:9200/' if not set. If ES is up and running but not accessible
by this default url, set up the env varialble (SEARCH_SITE) which points to
ES.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/oneops/display/issues/4#issuecomment-297064919>, or mute
the thread

**Comment by yrmallu** [comment]
Can you please share me the steps to setup and run elastic search and
logstash in oneops ?

**Comment by lkhusid** [comment]
Are you just running the Vagrant OneOps setup.   If so, it is just a bootstrap setup that does not support a few things incl.   ES,  monitoring and etc.   You would need a full-blown installation of OneOps for that.
Meanwhile, if you have questions about that - I would advise to post in "Setup" repo (https://github.com/oneops/setup).    Also, you can turn off cost related stuff section from displaying in UI
by setting *SHOW_COST* to 'false' in 'start_display.sh' script on your Vagrant setup.

**Comment by yrmallu** [comment]
Thanks for the information.

Yes. I'm running in Vagrant only. Can you please let me how setup and run
full fledged oneops i.e metrics and cost summary. Can you please guide ?

I don't want to hide cost. I want to show cost summary.

**Comment by lkhusid** [comment]
This is not a quick answer.    I strongly recommend you follow documentation (though it is not compete nor perfect at this point).

http://oneops.com/admin/

Basically it comes down to using your Vagrant OneOps base to bootstrap a real OneOps instance  (you can use the *setup* repo that has design yaml files to create OneOps assemblies or you can create the design of OneOps module platforms from scratch yourself) by creating an assembly and deploying it to the cloud of your choice. 

There is much to it of course.  Post in the setup repo and use OneOps slack channel to get more help.

**Comment by yrmallu** [comment]
@lkhusid Still cost summary is not working. Can you please provide the necessary changes we have to do in oneops to get it to be worked properly.
