### ISSUE TITLE
Create Api to retrieve available packs.

### ISSUE THREAD

**Issue by pointwisefixed** [oneops/display#98]
I think it would be useful to have an Api to retrieve the available packs. This could also go downstream to the oneops cli gem so we can get all available packs and event attributes available for every pack.

**Comment by kfilipovski** [comment]
I believe this is already available in the /catalog section. @lkhusid can you please confirm?

**Comment by pointwisefixed** [comment]
Hah! you are right, /catalogs/packs.json gives me the packs and from there I can figure out the resource url to retrieve an specific path info.

**Comment by lkhusid** [comment]
@pointwisefixed,  sorry for delayed response.   You figured it out on your own.    There is a whole spectrum of downstream API endpoints to get info about a pack and its components and its variables and possibly even policies.    The URLs are very much similar to how you would go after the corresponding stuff in design.     CLI had support for getting a list of available packs.  Though it may be broken at the moment.    The pack "browser" of the website was added only recently and I believe CLI has not been updated with corresponding commands.   I will check on the CLI command for packs and will let you know.

**Comment by lkhusid** [comment]
CLI has support to get available packs:

   `oo design packs`

I just updated the gem (ver *0.3.2*) to use proper API route and not to require assembly name switch.
