### ISSUE TITLE
Create Assembly Endpoint (REST API) does not allow you to add a team for your assembly.

### ISSUE THREAD

**Issue by pointwisefixed** [oneops/display#99]
Right now if i use the endpoint to create an assembly, It will create an assembly but it will not create the relationship between the assembly and me (or my team). This only happens when you do it through the UI. This would lead me to create phantom assemblies that have no teams and I cannot see or delete after I create them (I have done this). Because this bug is here, this also happens in the oneops cli gem too I believe.

**Comment by mosabua** [comment]
Issue tracking is migrated to Walmart JIRA and https://github.com/oneops/oneops.
